# Generated by Django 4.2.7 on 2023-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic_url",
            field=models.TextField(null=True),
        ),
    ]
