# Generated by Django 4.2.7 on 2023-11-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tides", "0002_alter_user_profile_pic_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_role",
            field=models.TextField(null=True),
        ),
    ]
