# Generated by Django 4.2.7 on 2023-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tides", "0003_job_skills_required_alter_job_job_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="project_report",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
