# Generated by Django 4.2.7 on 2023-11-07 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tides", "0004_alter_projects_project_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="applicant",
            field=models.ManyToManyField(
                null=True, related_name="jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
